

const mongoose = require("mongoose");

const Log  = require("../models/Log")


require('dotenv').config();


const seedData = [
  {
    actor: "priya.nair@company.com",
    role: "admin",
    action: "DELETE_USER",
    resource: "/api/users/334",
    resourceType: "USER",
    ipAddress: "192.168.1.45",
    region: "ap-south-1",
    severity: "HIGH",
    severityLevel: 3,
    status: "Unresolved",
    timestamp: new Date("2025-06-14T08:32:11Z"),
  },
  {
    actor: "arun.kumar@company.com",
    role: "manager",
    action: "CREATE_USER",
    resource: "/api/users",
    resourceType: "USER",
    ipAddress: "192.168.1.22",
    region: "ap-south-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-15T09:12:00Z"),
  },
  {
    actor: "meena.sharma@company.com",
    role: "support",
    action: "UPDATE_USER",
    resource: "/api/users/210",
    resourceType: "USER",
    ipAddress: "192.168.1.67",
    region: "us-east-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-15T10:25:00Z"),
  },
  {
    actor: "rahul.verma@company.com",
    role: "admin",
    action: "LOGIN",
    resource: "/api/auth/login",
    resourceType: "AUTH",
    ipAddress: "10.10.10.10",
    region: "eu-west-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-15T11:00:00Z"),
  },
  {
    actor: "john.doe@company.com",
    role: "user",
    action: "LOGIN",
    resource: "/api/auth/login",
    resourceType: "AUTH",
    ipAddress: "172.16.1.2",
    region: "us-east-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-16T08:20:00Z"),
  },
  {
    actor: "sneha.iyer@company.com",
    role: "admin",
    action: "DELETE_ORDER",
    resource: "/api/orders/102",
    resourceType: "ORDER",
    ipAddress: "192.168.5.10",
    region: "ap-south-1",
    severity: "CRITICAL",
    severityLevel: 4,
    status: "Unresolved",
    timestamp: new Date("2025-06-16T09:00:00Z"),
  },
  {
    actor: "vijay@company.com",
    role: "support",
    action: "VIEW_REPORT",
    resource: "/api/reports/11",
    resourceType: "REPORT",
    ipAddress: "10.0.0.22",
    region: "eu-west-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-16T09:45:00Z"),
  },
  {
    actor: "karthik@company.com",
    role: "manager",
    action: "UPDATE_ORDER",
    resource: "/api/orders/101",
    resourceType: "ORDER",
    ipAddress: "192.168.1.90",
    region: "us-east-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-16T10:00:00Z"),
  },
  {
    actor: "divya@company.com",
    role: "admin",
    action: "DELETE_PRODUCT",
    resource: "/api/products/50",
    resourceType: "PRODUCT",
    ipAddress: "192.168.2.1",
    region: "ap-south-1",
    severity: "HIGH",
    severityLevel: 3,
    status: "Resolved",
    timestamp: new Date("2025-06-16T11:15:00Z"),
  },
  {
    actor: "ramesh@company.com",
    role: "user",
    action: "LOGIN",
    resource: "/api/auth/login",
    resourceType: "AUTH",
    ipAddress: "10.20.30.40",
    region: "eu-west-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-17T08:00:00Z"),
  },
  {
    actor: "anita@company.com",
    role: "support",
    action: "RESET_PASSWORD",
    resource: "/api/users/90",
    resourceType: "USER",
    ipAddress: "192.168.10.10",
    region: "ap-south-1",
    severity: "HIGH",
    severityLevel: 3,
    status: "Unresolved",
    timestamp: new Date("2025-06-17T09:10:00Z"),
  },
  {
    actor: "mohan@company.com",
    role: "manager",
    action: "EXPORT_REPORT",
    resource: "/api/reports/export",
    resourceType: "REPORT",
    ipAddress: "10.100.1.2",
    region: "us-east-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-17T10:20:00Z"),
  },
  {
    actor: "keerthi@company.com",
    role: "admin",
    action: "CREATE_PRODUCT",
    resource: "/api/products",
    resourceType: "PRODUCT",
    ipAddress: "172.20.10.1",
    region: "eu-west-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-17T11:30:00Z"),
  },
  {
    actor: "bharath@company.com",
    role: "user",
    action: "LOGOUT",
    resource: "/api/auth/logout",
    resourceType: "AUTH",
    ipAddress: "192.168.1.101",
    region: "ap-south-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-18T08:00:00Z"),
  },
  {
    actor: "sanjay@company.com",
    role: "support",
    action: "UPDATE_PRODUCT",
    resource: "/api/products/80",
    resourceType: "PRODUCT",
    ipAddress: "10.10.1.1",
    region: "us-east-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-18T09:20:00Z"),
  },
  {
    actor: "pooja@company.com",
    role: "admin",
    action: "DELETE_PRODUCT",
    resource: "/api/products/81",
    resourceType: "PRODUCT",
    ipAddress: "172.16.10.2",
    region: "eu-west-1",
    severity: "CRITICAL",
    severityLevel: 4,
    status: "Unresolved",
    timestamp: new Date("2025-06-18T10:00:00Z"),
  },
  {
    actor: "naveen@company.com",
    role: "manager",
    action: "VIEW_REPORT",
    resource: "/api/reports/7",
    resourceType: "REPORT",
    ipAddress: "192.168.1.11",
    region: "ap-south-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-18T11:00:00Z"),
  },
  {
    actor: "akash@company.com",
    role: "user",
    action: "LOGIN",
    resource: "/api/auth/login",
    resourceType: "AUTH",
    ipAddress: "10.10.10.15",
    region: "us-east-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-19T08:40:00Z"),
  },
  {
    actor: "hari@company.com",
    role: "admin",
    action: "UPDATE_USER",
    resource: "/api/users/400",
    resourceType: "USER",
    ipAddress: "192.168.1.70",
    region: "eu-west-1",
    severity: "HIGH",
    severityLevel: 3,
    status: "Resolved",
    timestamp: new Date("2025-06-19T09:45:00Z"),
  },
  {
    actor: "lavanya@company.com",
    role: "support",
    action: "DELETE_USER",
    resource: "/api/users/401",
    resourceType: "USER",
    ipAddress: "172.18.0.5",
    region: "ap-south-1",
    severity: "CRITICAL",
    severityLevel: 4,
    status: "Unresolved",
    timestamp: new Date("2025-06-19T10:15:00Z"),
  },
  {
    actor: "gokul@company.com",
    role: "manager",
    action: "CREATE_ORDER",
    resource: "/api/orders",
    resourceType: "ORDER",
    ipAddress: "192.168.4.10",
    region: "us-east-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-20T08:30:00Z"),
  },
  {
    actor: "deepa@company.com",
    role: "admin",
    action: "DELETE_ORDER",
    resource: "/api/orders/500",
    resourceType: "ORDER",
    ipAddress: "10.1.1.1",
    region: "ap-south-1",
    severity: "HIGH",
    severityLevel: 3,
    status: "Resolved",
    timestamp: new Date("2025-06-20T09:30:00Z"),
  },
  {
    actor: "surya@company.com",
    role: "support",
    action: "UPDATE_ORDER",
    resource: "/api/orders/502",
    resourceType: "ORDER",
    ipAddress: "192.168.100.2",
    region: "eu-west-1",
    severity: "MEDIUM",
    severityLevel: 2,
    status: "Resolved",
    timestamp: new Date("2025-06-20T10:20:00Z"),
  },
  {
    actor: "manoj@company.com",
    role: "user",
    action: "LOGIN",
    resource: "/api/auth/login",
    resourceType: "AUTH",
    ipAddress: "172.31.0.2",
    region: "us-east-1",
    severity: "LOW",
    severityLevel: 1,
    status: "Resolved",
    timestamp: new Date("2025-06-20T11:10:00Z"),
  },
  {
    actor: "kavitha@company.com",
    role: "admin",
    action: "DELETE_USER",
    resource: "/api/users/999",
    resourceType: "USER",
    ipAddress: "192.168.200.1",
    region: "ap-south-1",
    severity: "CRITICAL",
    severityLevel: 4,
    status: "Unresolved",
    timestamp: new Date("2025-06-21T09:00:00Z"),
  },
];





const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);

    console.log("MongoDB Connected");

    await Log.deleteMany();

    console.log("Old Logs Removed");

    await Log.insertMany(seedData);

    console.log(`${seedData.length} Logs Inserted Successfully`);

    process.exit(0);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedDatabase();